//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: ASR.ice
//  Source: ASR.idsl
//
//******************************************************************
#ifndef ROBOCOMPASR_ICE
#define ROBOCOMPASR_ICE
module RoboCompASR
{
	sequence <int> audioVector;
	interface ASR
	{
		string getLastPhrase ();
		void listenVector (audioVector audio);
		void listenWav (string path);
		bool phraseAvailable ();
		void resetPhraseBuffer ();
	};
};

#endif
