# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'therapist.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setGeometry(QtCore.QRect(0, 0, 798, 550))
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(30, 10, 256, 61))
        self.textEdit_2.setAutoFillBackground(True)
        self.textEdit_2.setStyleSheet("background-color: transparent;")
        self.textEdit_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.hablaButton = QtWidgets.QPushButton(Dialog)
        self.hablaButton.setGeometry(QtCore.QRect(520, 120, 201, 101))
        self.hablaButton.setObjectName("hablaButton")
        self.textEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(30, 240, 256, 61))
        self.textEdit_3.setAutoFillBackground(True)
        self.textEdit_3.setStyleSheet("background-color: transparent;")
        self.textEdit_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textEdit_3.setReadOnly(True)
        self.textEdit_3.setObjectName("textEdit_3")
        self.textoHablado = QtWidgets.QPlainTextEdit(Dialog)
        self.textoHablado.setGeometry(QtCore.QRect(40, 40, 441, 211))
        self.textoHablado.setObjectName("textoHablado")
        self.textoEscuchado = QtWidgets.QPlainTextEdit(Dialog)
        self.textoEscuchado.setGeometry(QtCore.QRect(40, 280, 441, 71))
        self.textoEscuchado.setObjectName("textoEscuchado")
        self.escuchaButton = QtWidgets.QPushButton(Dialog)
        self.escuchaButton.setGeometry(QtCore.QRect(520, 320, 201, 41))
        self.escuchaButton.setObjectName("escuchaButton")
        self.autoMode = QtWidgets.QCheckBox(Dialog)
        self.autoMode.setGeometry(QtCore.QRect(170, 420, 211, 51))
        self.autoMode.setObjectName("autoMode")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(390, 430, 171, 41))
        self.pushButton.setObjectName("pushButton")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(-60, 400, 891, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(-60, 480, 891, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Ui_Dialog", "Dialog"))
        self.hablaButton.setText(_translate("Ui_Dialog", "EBO HABLA"))
        self.escuchaButton.setText(_translate("Ui_Dialog", "EBO ESCUCHA"))
        self.autoMode.setText(_translate("Ui_Dialog", "Modo Automático"))
        self.pushButton.setText(_translate("Ui_Dialog", "FINALIZAR JUEGO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
