//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: LLM.ice
//  Source: LLM.idsl
//
//******************************************************************
#ifndef ROBOCOMPLLM_ICE
#define ROBOCOMPLLM_ICE
module RoboCompLLM
{
	interface LLM
	{
		string generateResponse ();
	};
};

#endif
